feat: support `FormData`
fastify/light-my-request pull request #286
Opened 2024-04-05 10:00 UTC by climba03003

Support FormData and provide the `Content-Type` header automatically.

#### Checklist

- [ ] run `npm run test` and `npm run benchmark`
- [ ] tests and/or benchmarks are included
- [ ] documentation is changed or added
- [ ] commit message and code follows the [Developer's Certification of Origin](https://github.com/fastify/.github/blob/master/CONTRIBUTING.md#developers-certificate-of-origin-11)
      and the [Code of conduct](https://github.com/fastify/.github/blob/master/CODE_OF_CONDUCT.md)

2024-04-05 10:18 UTC, climba03003 commented
The coverage is really broken in supporting `FormData`.
It can only be used in `node > 18` but we still supporting `14 <= node < 18`.

2024-04-06 14:11 UTC, climba03003 commented on lib/form-data.js
> +function formDataToStream (formdata) {
```suggestion
/*
  partial code extraction and refactoring of `undici`.
  MIT License. https://github.com/nodejs/undici/blob/043d8f1a89f606b1db259fc71f4c9bc8eb2aa1e6/lib/web/fetch/LICENSE
  Reference https://github.com/nodejs/undici/blob/043d8f1a89f606b1db259fc71f4c9bc8eb2aa1e6/lib/web/fetch/body.js#L102-L168
*/
function formDataToStream (formdata) {
```

2024-04-08 07:19 UTC, mcollina requested changes
Amazing work! Can you add a test for Node v14 and v16?

2024-04-08 07:19 UTC, mcollina commented on test/index.test.js
> +  if (parseInt(process.versions.node.split('.', 1)[0], 10) < 18) {
please use the native skip functionality

2024-04-08 07:32 UTC, climba03003 commented on test/index.test.js
> +  const { FormData } = require('undici')
I see a way to test in `node@14` and `node@16` now.
It requires to mix `undici` and `node:buffer` to support both `Blob` and `FormData` in old release line.

2024-04-08 08:04 UTC, climba03003 commented on test/index.test.js
> +runFormDataUnitTest('formdata-node', { FormData: require('formdata-node').FormData, Blob: require('formdata-node').Blob })
Coverage should be fine for all supported node version.
`undici` only supports `FormData` higher than `node@16`.
So, we need `formdata-node` for `node@14`.

It also show that we are not limited to `undici` implementation only, but support all spec compliance `FormData`

2024-04-08 09:48 UTC, mcollina approved these changes
lgtm

2024-04-10 19:52 UTC, metcoder95 approved these changes

2024-04-10 20:22 UTC, merged